#!/bin/tcsh -f

set scratchpath=/tmp
set logo=emblem.pnm
set size=128
set mypnm=`mktemp /tmp/pnm.XXXXXX`
set bg=bg"$size".pnm
set gallery=./gallery
set icons=$gallery/icons

# if ( "$4" != "" && ! -e "$gallery/$4" ) mkdir "$gallery/$4"; chmod 0777 "$gallery/$4"
# if ( "$4" != "" && ! -e "$gallery/icons/$4" ) mkdir "$gallery/icons/$4"; chmod 0777 "$gallery/icons/$4"


#djpeg
jpegtopnm -exif=$scratchpath/$1.exif  < $scratchpath/$1.JPG > $mypnm

if ( $? != 0 ) then
    rm -f $scratchpath/$1.JPG
    rm -f $scratchpath/$1.exif
    rm -f $mypnm
    exit 1
endif
rm -f $scratchpath/$1.JPG
set filesize = `pnmfile $mypnm`;

#prepare an icon
set cmd=`echo "$filesize" | awk '$4>=$6&&$4<1.5*$6{ print "cat"}$4>=1.5*$6{marg=int(($4-1.5*$6)/2); print "pnmcut -left ",marg,"-right",$4-marg-1}$4<$6{marg=int(($6-$4)/2); print "pnmcut -top ",marg,"-bottom",$6-marg-1}'`

cat $mypnm | `echo $cmd` | pnmscale -ysize `expr $size - 2` | pnmmargin -black 1 | pnmtojpeg --optimize --quality=95 >  $icons/$4/$1-s.jpg

# Condition the picture
set cmd=`echo "$filesize" | awk 'BEGIN{area=1280*900}$4*$6>area{printf "pnmscale %f", sqrt(area/($4*$6))}$4*$6<=area{print "cat"}'`

cat $mypnm | `echo $cmd` | pnmpaste $logo $2 $3 | pnmtojpeg --exif=$scratchpath/$1.exif  --optimize --quality=95  --progressive  > $gallery/$4/$1.jpg

if ( $? != 0 ) then
    cat $mypnm | `echo $cmd` | pnmpaste $logo $2 $3 | pnmtojpeg --optimize --quality=85  --progressive  > $gallery/$4/$1.jpg
#    cat $mypnm | `echo $cmd` | pnmtojpeg --optimize --quality=85  --progressive  > $gallery/$4/$1.jpg
endif

if ( $? != 0 ) then
    cat $mypnm | `echo $cmd` | pnmtojpeg --optimize --quality=95  --progressive  > $gallery/$4/$1.jpg
endif

rm -f $scratchpath/$1.exif
rm -f $mypnm
